version: 0.2
phases:
  install:
    runtime-versions:
      java: corretto17
  pre_build:
    commands:
      - echo Test started on `date`
      - mvn clean compile test
  build:
    commands:
      - echo Build started on `date`
      - mvn package shade:shade
      - mv target/sac-0.0.1-SNAPSHOT.jar
      - unzip sac-0.0.1-SNAPSHOT.jar
      - rm -rf target tst src buildspec.yml pom.xml sac-0.0.1-SNAPSHOT.jar
      - aws cloudformation package --template-file template.yaml
  post_build:
    commands:
      - echo Build completed on `date` !!!
artifacts:
  files:
    - target/sac-0.0.1-SNAPSHOT.jar
    - template.yaml
