version: 0.2

phases:
  build:
    commands:
      - echo Packaging app on `date`
      - mvn clean package
      - aws cloudformation package --template-file template.yaml --s3-bucket wwwb-release --output-template-file output-sam.yaml
  post_build:
    commands:
      - echo App packaged on `date`.
artifacts:
  type: jar
  files:
    - "target/sac-0.0.1-SNAPSHOT.jar"
    - "template.yaml"
    - "output-sam.yaml"
  discard-paths: yes
